- hosts: bbdd
  become: yes
  tasks:
  - name: "apt-get update"
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: "install redis"
    apt:
      name: ['redis']
      state: latest

  - name: "install mysql"
    apt:
      name: ['mysql-server']
      state: latest